# Generated by Django 5.1.2 on 2024-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_on',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='available_seats',
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
