# Generated by Django 5.1.1 on 2024-10-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_rename_date_booking_booked_on_alter_tour_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/default_avatar.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='images/default_avatar.png', upload_to='tours/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
