# Generated by Django 5.1.1 on 2024-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_remove_userprofile_bio_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
