# Generated by Django 5.1.1 on 2024-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_tour_is_offer_tour_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='is_offer',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='original_price',
        ),
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tours/images'),
        ),
    ]
