# Generated by Django 5.1.1 on 2024-10-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
