# Generated by Django 5.1.1 on 2024-10-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_rename_text_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
