# Generated by Django 5.1.1 on 2024-11-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_booking_payment_status_booking_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
